name: 'checkout-file'
description: 'Greet someone and record the time'
author: 'Bhacaz'

branding:
  icon: 'download'
  color: 'green'
  
inputs:
  files:  # id of input
    description: 'Files to checkout from the repo'
    required: true

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: ${{ github.action_path }}/script.sh
