name: 'checkout-file'
description: 'Checkout only certain files'
author: 'Bhacaz'

branding:
  icon: 'download'
  color: 'blue'

inputs:
  files:
    description: 'Files to checkout from the repo'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
